// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/luxun9527/gex/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upsert_service_config",
				Handler: UpsertServiceConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_service_config",
				Handler: GetServiceConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload_template_file",
				Handler: UploadTemplateFileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/v1"),
	)
}
