// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/luxun9527/gex/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upsert_service_config",
				Handler: UpsertServiceConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_service_config",
				Handler: GetServiceConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get_symbol_list",
				Handler: GetSymbolListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add_symbol",
				Handler: AddSymbolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_symbol",
				Handler: UpdateSymbolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add_coin",
				Handler: AddCoinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_coin",
				Handler: UpdateCoinHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get_coin_list",
				Handler: GetCoinListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add_error_code",
				Handler: AddErrorCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get_error_code_list",
				Handler: GetErrorCodeListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_error_code",
				Handler: UpdateErrorCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync_error_code",
				Handler: SyncErrorCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync_coin_config",
				Handler: SyncCoinConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync_symbol_config",
				Handler: SyncSymbolConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/v1"),
	)
}
