// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: app/quotes/kline/rpc/pb/kline.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KlineType int32

const (
	KlineType_Unknown KlineType = 0
	// 1分钟
	KlineType_Min1 KlineType = 1
	// 5分钟
	KlineType_Min5 KlineType = 2
	// 10分钟
	KlineType_Min10 KlineType = 3
	// 15分钟
	KlineType_Min15 KlineType = 4
	// 30分钟
	KlineType_Min30 KlineType = 5
	// 1小时
	KlineType_Hour1 KlineType = 6
	// 4小时
	KlineType_Hour4 KlineType = 7
	// 1天
	KlineType_Day1 KlineType = 8
	// 1周
	KlineType_Week1 KlineType = 9
	// 1个月
	KlineType_Month1 KlineType = 10
)

// Enum value maps for KlineType.
var (
	KlineType_name = map[int32]string{
		0:  "Unknown",
		1:  "Min1",
		2:  "Min5",
		3:  "Min10",
		4:  "Min15",
		5:  "Min30",
		6:  "Hour1",
		7:  "Hour4",
		8:  "Day1",
		9:  "Week1",
		10: "Month1",
	}
	KlineType_value = map[string]int32{
		"Unknown": 0,
		"Min1":    1,
		"Min5":    2,
		"Min10":   3,
		"Min15":   4,
		"Min30":   5,
		"Hour1":   6,
		"Hour4":   7,
		"Day1":    8,
		"Week1":   9,
		"Month1":  10,
	}
)

func (x KlineType) Enum() *KlineType {
	p := new(KlineType)
	*p = x
	return p
}

func (x KlineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KlineType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_quotes_kline_rpc_pb_kline_proto_enumTypes[0].Descriptor()
}

func (KlineType) Type() protoreflect.EnumType {
	return &file_app_quotes_kline_rpc_pb_kline_proto_enumTypes[0]
}

func (x KlineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KlineType.Descriptor instead.
func (KlineType) EnumDescriptor() ([]byte, []int) {
	return file_app_quotes_kline_rpc_pb_kline_proto_rawDescGZIP(), []int{0}
}

type GetKlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开始时间
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 结束时间
	EntTime int64 `protobuf:"varint,2,opt,name=ent_time,json=entTime,proto3" json:"ent_time,omitempty"`
	// k线类型
	KlineType KlineType `protobuf:"varint,3,opt,name=kline_type,json=klineType,proto3,enum=pb.KlineType" json:"kline_type,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetKlineReq) Reset() {
	*x = GetKlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineReq) ProtoMessage() {}

func (x *GetKlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineReq.ProtoReflect.Descriptor instead.
func (*GetKlineReq) Descriptor() ([]byte, []int) {
	return file_app_quotes_kline_rpc_pb_kline_proto_rawDescGZIP(), []int{0}
}

func (x *GetKlineReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetKlineReq) GetEntTime() int64 {
	if x != nil {
		return x.EntTime
	}
	return 0
}

func (x *GetKlineReq) GetKlineType() KlineType {
	if x != nil {
		return x.KlineType
	}
	return KlineType_Unknown
}

func (x *GetKlineReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetKlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KlineList []*GetKlineResp_Kline `protobuf:"bytes,1,rep,name=kline_list,json=klineList,proto3" json:"kline_list,omitempty"`
}

func (x *GetKlineResp) Reset() {
	*x = GetKlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineResp) ProtoMessage() {}

func (x *GetKlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineResp.ProtoReflect.Descriptor instead.
func (*GetKlineResp) Descriptor() ([]byte, []int) {
	return file_app_quotes_kline_rpc_pb_kline_proto_rawDescGZIP(), []int{1}
}

func (x *GetKlineResp) GetKlineList() []*GetKlineResp_Kline {
	if x != nil {
		return x.KlineList
	}
	return nil
}

type GetKlineResp_Kline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开
	Open string `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	// 高
	High string `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	// 低
	Low string `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	// 收
	Close string `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	// 成交额 计价币数量
	Volume string `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// 成交量 基础币数量
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 结束时间
	EndTime int64 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// 涨跌幅
	Range string `protobuf:"bytes,9,opt,name=range,proto3" json:"range,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetKlineResp_Kline) Reset() {
	*x = GetKlineResp_Kline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineResp_Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineResp_Kline) ProtoMessage() {}

func (x *GetKlineResp_Kline) ProtoReflect() protoreflect.Message {
	mi := &file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineResp_Kline.ProtoReflect.Descriptor instead.
func (*GetKlineResp_Kline) Descriptor() ([]byte, []int) {
	return file_app_quotes_kline_rpc_pb_kline_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetKlineResp_Kline) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *GetKlineResp_Kline) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *GetKlineResp_Kline) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *GetKlineResp_Kline) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *GetKlineResp_Kline) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetKlineResp_Kline) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetKlineResp_Kline) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetKlineResp_Kline) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetKlineResp_Kline) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *GetKlineResp_Kline) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_app_quotes_kline_rpc_pb_kline_proto protoreflect.FileDescriptor

var file_app_quotes_kline_rpc_pb_kline_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x70, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x2f, 0x6b, 0x6c, 0x69,
	0x6e, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x6c, 0x69,
	0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xb7, 0x02, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x6b, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x09, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x1a, 0xef, 0x01, 0x0a, 0x05, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f,
	0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x2a, 0x84, 0x01, 0x0a, 0x09, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x31, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x35,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x31, 0x30, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x4d, 0x69, 0x6e, 0x31, 0x35, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x33,
	0x30, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x72, 0x31, 0x10, 0x06, 0x12, 0x09,
	0x0a, 0x05, 0x48, 0x6f, 0x75, 0x72, 0x34, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x61, 0x79,
	0x31, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x65, 0x65, 0x6b, 0x31, 0x10, 0x09, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x31, 0x10, 0x0a, 0x32, 0x3d, 0x0a, 0x0c, 0x4b, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4b,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_quotes_kline_rpc_pb_kline_proto_rawDescOnce sync.Once
	file_app_quotes_kline_rpc_pb_kline_proto_rawDescData = file_app_quotes_kline_rpc_pb_kline_proto_rawDesc
)

func file_app_quotes_kline_rpc_pb_kline_proto_rawDescGZIP() []byte {
	file_app_quotes_kline_rpc_pb_kline_proto_rawDescOnce.Do(func() {
		file_app_quotes_kline_rpc_pb_kline_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_quotes_kline_rpc_pb_kline_proto_rawDescData)
	})
	return file_app_quotes_kline_rpc_pb_kline_proto_rawDescData
}

var file_app_quotes_kline_rpc_pb_kline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_quotes_kline_rpc_pb_kline_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_quotes_kline_rpc_pb_kline_proto_goTypes = []interface{}{
	(KlineType)(0),             // 0: pb.KlineType
	(*GetKlineReq)(nil),        // 1: pb.GetKlineReq
	(*GetKlineResp)(nil),       // 2: pb.GetKlineResp
	(*GetKlineResp_Kline)(nil), // 3: pb.GetKlineResp.Kline
}
var file_app_quotes_kline_rpc_pb_kline_proto_depIdxs = []int32{
	0, // 0: pb.GetKlineReq.kline_type:type_name -> pb.KlineType
	3, // 1: pb.GetKlineResp.kline_list:type_name -> pb.GetKlineResp.Kline
	1, // 2: pb.KlineService.GetKline:input_type -> pb.GetKlineReq
	2, // 3: pb.KlineService.GetKline:output_type -> pb.GetKlineResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_quotes_kline_rpc_pb_kline_proto_init() }
func file_app_quotes_kline_rpc_pb_kline_proto_init() {
	if File_app_quotes_kline_rpc_pb_kline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quotes_kline_rpc_pb_kline_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineResp_Kline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_quotes_kline_rpc_pb_kline_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_quotes_kline_rpc_pb_kline_proto_goTypes,
		DependencyIndexes: file_app_quotes_kline_rpc_pb_kline_proto_depIdxs,
		EnumInfos:         file_app_quotes_kline_rpc_pb_kline_proto_enumTypes,
		MessageInfos:      file_app_quotes_kline_rpc_pb_kline_proto_msgTypes,
	}.Build()
	File_app_quotes_kline_rpc_pb_kline_proto = out.File
	file_app_quotes_kline_rpc_pb_kline_proto_rawDesc = nil
	file_app_quotes_kline_rpc_pb_kline_proto_goTypes = nil
	file_app_quotes_kline_rpc_pb_kline_proto_depIdxs = nil
}
