// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: app/quotes/kline/rpc/pb/kline.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KlineService_GetKline_FullMethodName = "/pb.KlineService/GetKline"
)

// KlineServiceClient is the client API for KlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KlineServiceClient interface {
	// 获取k线
	GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error)
}

type klineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKlineServiceClient(cc grpc.ClientConnInterface) KlineServiceClient {
	return &klineServiceClient{cc}
}

func (c *klineServiceClient) GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error) {
	out := new(GetKlineResp)
	err := c.cc.Invoke(ctx, KlineService_GetKline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KlineServiceServer is the server API for KlineService service.
// All implementations must embed UnimplementedKlineServiceServer
// for forward compatibility
type KlineServiceServer interface {
	// 获取k线
	GetKline(context.Context, *GetKlineReq) (*GetKlineResp, error)
	mustEmbedUnimplementedKlineServiceServer()
}

// UnimplementedKlineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKlineServiceServer struct {
}

func (UnimplementedKlineServiceServer) GetKline(context.Context, *GetKlineReq) (*GetKlineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKline not implemented")
}
func (UnimplementedKlineServiceServer) mustEmbedUnimplementedKlineServiceServer() {}

// UnsafeKlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KlineServiceServer will
// result in compilation errors.
type UnsafeKlineServiceServer interface {
	mustEmbedUnimplementedKlineServiceServer()
}

func RegisterKlineServiceServer(s grpc.ServiceRegistrar, srv KlineServiceServer) {
	s.RegisterService(&KlineService_ServiceDesc, srv)
}

func _KlineService_GetKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KlineServiceServer).GetKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KlineService_GetKline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KlineServiceServer).GetKline(ctx, req.(*GetKlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KlineService_ServiceDesc is the grpc.ServiceDesc for KlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KlineService",
	HandlerType: (*KlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKline",
			Handler:    _KlineService_GetKline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/quotes/kline/rpc/pb/kline.proto",
}
