// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/luxun9527/gex/app/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create_order",
					Handler: CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cancel_order",
					Handler: CancelOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_order_list",
					Handler: GetOrderListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/order/v1"),
	)
}
