// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: common/proto/enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 买卖方向
type Side int32

const (
	// 未知
	Side_UnknownSide Side = 0
	// 买
	Side_Buy Side = 1
	// 卖
	Side_Sell Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "UnknownSide",
		1: "Buy",
		2: "Sell",
	}
	Side_value = map[string]int32{
		"UnknownSide": 0,
		"Buy":         1,
		"Sell":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_common_proto_enum_enum_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_enum_enum_proto_rawDescGZIP(), []int{0}
}

// 订单类型
type OrderType int32

const (
	// 未知
	OrderType_UnknownOrderType OrderType = 0
	// 市价单
	OrderType_MO OrderType = 1
	// 限价单
	OrderType_LO OrderType = 2
	// 立即全部成交否則取消
	OrderType_FOK OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "UnknownOrderType",
		1: "MO",
		2: "LO",
		3: "FOK",
	}
	OrderType_value = map[string]int32{
		"UnknownOrderType": 0,
		"MO":               1,
		"LO":               2,
		"FOK":              3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enum_enum_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_common_proto_enum_enum_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_enum_enum_proto_rawDescGZIP(), []int{1}
}

// 订单状态
type OrderStatus int32

const (
	// 未知
	OrderStatus_UnknownOrderStatus OrderStatus = 0
	// 新建未成交
	OrderStatus_NewCreated OrderStatus = 1
	// 部分成交
	OrderStatus_PartFilled OrderStatus = 2
	// 全部成交
	OrderStatus_ALLFilled OrderStatus = 3
	// 撤销
	OrderStatus_Canceled OrderStatus = 4
	// 废弃
	OrderStatus_Wasted OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UnknownOrderStatus",
		1: "NewCreated",
		2: "PartFilled",
		3: "ALLFilled",
		4: "Canceled",
		5: "Wasted",
	}
	OrderStatus_value = map[string]int32{
		"UnknownOrderStatus": 0,
		"NewCreated":         1,
		"PartFilled":         2,
		"ALLFilled":          3,
		"Canceled":           4,
		"Wasted":             5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enum_enum_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enum_enum_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_enum_enum_proto_rawDescGZIP(), []int{2}
}

// 成交角色
type FillRole int32

const (
	// 未知
	FillRole_UnknownFillRole FillRole = 0
	// taker
	FillRole_Taker FillRole = 1
	// maker
	FillRole_Maker FillRole = 2
)

// Enum value maps for FillRole.
var (
	FillRole_name = map[int32]string{
		0: "UnknownFillRole",
		1: "Taker",
		2: "Maker",
	}
	FillRole_value = map[string]int32{
		"UnknownFillRole": 0,
		"Taker":           1,
		"Maker":           2,
	}
)

func (x FillRole) Enum() *FillRole {
	p := new(FillRole)
	*p = x
	return p
}

func (x FillRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FillRole) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enum_enum_proto_enumTypes[3].Descriptor()
}

func (FillRole) Type() protoreflect.EnumType {
	return &file_common_proto_enum_enum_proto_enumTypes[3]
}

func (x FillRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FillRole.Descriptor instead.
func (FillRole) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_enum_enum_proto_rawDescGZIP(), []int{3}
}

// 报价类型
type Quote int32

const (
	Quote_UnknownQuote Quote = 0
	// 卖出价
	Quote_Ask Quote = 1
	// 买入价
	Quote_Bid Quote = 2
)

// Enum value maps for Quote.
var (
	Quote_name = map[int32]string{
		0: "UnknownQuote",
		1: "Ask",
		2: "Bid",
	}
	Quote_value = map[string]int32{
		"UnknownQuote": 0,
		"Ask":          1,
		"Bid":          2,
	}
)

func (x Quote) Enum() *Quote {
	p := new(Quote)
	*p = x
	return p
}

func (x Quote) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quote) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enum_enum_proto_enumTypes[4].Descriptor()
}

func (Quote) Type() protoreflect.EnumType {
	return &file_common_proto_enum_enum_proto_enumTypes[4]
}

func (x Quote) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quote.Descriptor instead.
func (Quote) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_enum_enum_proto_rawDescGZIP(), []int{4}
}

var File_common_proto_enum_enum_proto protoreflect.FileDescriptor

var file_common_proto_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x2a, 0x2a, 0x0a, 0x04, 0x53, 0x69,
	0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x53, 0x69, 0x64,
	0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x53, 0x65, 0x6c, 0x6c, 0x10, 0x02, 0x2a, 0x3a, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x4f, 0x10,
	0x01, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x4f, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x4f, 0x4b,
	0x10, 0x03, 0x2a, 0x6e, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x74, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4c, 0x4c,
	0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x61, 0x73, 0x74, 0x65, 0x64,
	0x10, 0x05, 0x2a, 0x35, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13,
	0x0a, 0x0f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x69, 0x6c, 0x6c, 0x52, 0x6f, 0x6c,
	0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x61, 0x6b, 0x65, 0x72, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x10, 0x02, 0x2a, 0x2b, 0x0a, 0x05, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x69, 0x64, 0x10, 0x02, 0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75,
	0x6d, 0x3b, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_enum_enum_proto_rawDescOnce sync.Once
	file_common_proto_enum_enum_proto_rawDescData = file_common_proto_enum_enum_proto_rawDesc
)

func file_common_proto_enum_enum_proto_rawDescGZIP() []byte {
	file_common_proto_enum_enum_proto_rawDescOnce.Do(func() {
		file_common_proto_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_enum_enum_proto_rawDescData)
	})
	return file_common_proto_enum_enum_proto_rawDescData
}

var file_common_proto_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_enum_enum_proto_goTypes = []interface{}{
	(Side)(0),        // 0: commonEnum.Side
	(OrderType)(0),   // 1: commonEnum.OrderType
	(OrderStatus)(0), // 2: commonEnum.OrderStatus
	(FillRole)(0),    // 3: commonEnum.FillRole
	(Quote)(0),       // 4: commonEnum.Quote
}
var file_common_proto_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_enum_enum_proto_init() }
func file_common_proto_enum_enum_proto_init() {
	if File_common_proto_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_enum_enum_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_enum_enum_proto_goTypes,
		DependencyIndexes: file_common_proto_enum_enum_proto_depIdxs,
		EnumInfos:         file_common_proto_enum_enum_proto_enumTypes,
	}.Build()
	File_common_proto_enum_enum_proto = out.File
	file_common_proto_enum_enum_proto_rawDesc = nil
	file_common_proto_enum_enum_proto_goTypes = nil
	file_common_proto_enum_enum_proto_depIdxs = nil
}
