// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAsset = "asset"

// Asset mapped from table <asset>
type Asset struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`
	Username     string `gorm:"column:username;comment:用户名" json:"username"`
	CoinID       int32  `gorm:"column:coin_id;not null;comment:数字货币ID" json:"coin_id"`
	CoinName     string `gorm:"column:coin_name;not null;comment:数字货币名称" json:"coin_name"`
	AvailableQty string `gorm:"column:available_qty;not null;comment:可用余额" json:"available_qty"`
	FrozenQty    string `gorm:"column:frozen_qty;not null;comment:冻结金额" json:"frozen_qty"`
	CreatedAt    int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt    int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`
}

// TableName Asset's table name
func (*Asset) TableName() string {
	return TableNameAsset
}
