// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type UpsertServiceConfigReq struct {
	Key        string `json:"key"`         //交易对
	ConfigData string `json:"config_data"` //配置
}

type GetServiceConfigReq struct {
	Key string `json:"key"`
}

type GetServiceConfigResp struct {
	ConfigData string `json:"config_data"`
}

type UploadTemplateFileReq struct {
	ServiceName string `form:"service_name"` //服务名
	Symbol      string `form:"symbol"`       //交易对
}
