// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEntrustOrder = "entrust_order"

// EntrustOrder mapped from table <entrust_order>
type EntrustOrder struct {
	ID             int64  `gorm:"column:id;primaryKey;comment:序号 主键 雪花算法生成，递增" json:"id"`
	OrderID        string `gorm:"column:order_id;not null;comment:订单号" json:"order_id"`
	UserID         int64  `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`
	SymbolID       int32  `gorm:"column:symbol_id;not null;comment:交易对ID" json:"symbol_id"`
	SymbolName     string `gorm:"column:symbol_name;not null;comment:交易对名称" json:"symbol_name"`
	Qty            string `gorm:"column:qty;not null;comment:下单数量" json:"qty"`
	Price          string `gorm:"column:price;not null;comment:价格" json:"price"`
	Side           int32  `gorm:"column:side;not null;comment:方向1买 2卖" json:"side"`
	Amount         string `gorm:"column:amount;not null;comment:金额" json:"amount"`
	Status         int32  `gorm:"column:status;not null;comment:状态1新订单2部分成交 3全部成交，4撤销，5无效订单" json:"status"`
	OrderType      int32  `gorm:"column:order_type;not null;comment:订单类型1市价单2限价单" json:"order_type"`
	FilledQty      string `gorm:"column:filled_qty;not null;comment:成交数量" json:"filled_qty"`
	UnFilledQty    string `gorm:"column:un_filled_qty;not null;comment:未成交数量" json:"un_filled_qty"`
	FilledAvgPrice string `gorm:"column:filled_avg_price;not null;comment:成交均价" json:"filled_avg_price"`
	FilledAmount   string `gorm:"column:filled_amount;not null;comment:成交金额" json:"filled_amount"`
	UnFilledAmount string `gorm:"column:un_filled_amount;not null;comment:未成交金额" json:"un_filled_amount"`
	CreatedAt      int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt      int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`
	DeletedAt      int64  `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`
}

// TableName EntrustOrder's table name
func (*EntrustOrder) TableName() string {
	return TableNameEntrustOrder
}
