// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Coin:      newCoin(db, opts...),
		ErrorCode: newErrorCode(db, opts...),
		Symbol:    newSymbol(db, opts...),
		User:      newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Coin      coin
	ErrorCode errorCode
	Symbol    symbol
	User      user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Coin:      q.Coin.clone(db),
		ErrorCode: q.ErrorCode.clone(db),
		Symbol:    q.Symbol.clone(db),
		User:      q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Coin:      q.Coin.replaceDB(db),
		ErrorCode: q.ErrorCode.replaceDB(db),
		Symbol:    q.Symbol.replaceDB(db),
		User:      q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Coin      *coinDo
	ErrorCode *errorCodeDo
	Symbol    *symbolDo
	User      *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Coin:      q.Coin.WithContext(ctx),
		ErrorCode: q.ErrorCode.WithContext(ctx),
		Symbol:    q.Symbol.WithContext(ctx),
		User:      q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
