FROM docker.1panel.live/library/busybox
WORKDIR /app

COPY ../../bin/accountapi /app/accountapi
COPY ../../app/account/api/etc/account.yaml /app/account.yaml

#COPY ADD 命令 复制的文件 已dockerfile文件为开始位置找 https://blog.csdn.net/Myuhua/article/details/107552813