// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type GetCaptchaResp struct {
	Captch string `json:"captch"`
}

type RegisterReq struct {
	Username        string `json:"username"`              //用户名
	Password        string `json:"password"`              //密码
	ConfirmPassword string `json:"confirm_password"`      //确认密码
	PhoneNumber     int64  `json:"phone_number,optional"` //手机号
	Captcha         int64  `json:"captcha,optional"`      //验证
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Uid        int64  `json:"uid"`         //uid
	Username   string `json:"username"`    //用户名
	Token      string `json:"token"`       //token
	ExpireTime int64  `json:"expire_time"` //到期时间
}

type AssetInfo struct {
	Id           int64  `json:"id"`            //id
	CoinName     string `json:"coin_name"`     //币种名称
	CoinID       int32  `json:"coin_id"`       //币种id
	AvailableQty string `json:"available_qty"` //可用数量
	FrozenQty    string `json:"frozen_qty"`    //冻结数量
}

type GetUserAssetListResp struct {
	AssetList []*AssetInfo `json:"asset_list"`
}

type ValidateTokenReq struct {
	Token string `json:"token"`
}

type UserInfo struct {
	Uid      string `json:"uid"`
	Username string `json:"username"`
}

type ValidateTokenResp struct {
	UserInfo *UserInfo `json:"user_info"`
}

type AddUserAssetReq struct {
	CoinName string `json:"coin_name"`
	Qty      string `json:"qty"`
}
