// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: app/match/rpc/pb/match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDepthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 档位
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetDepthReq) Reset() {
	*x = GetDepthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthReq) ProtoMessage() {}

func (x *GetDepthReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthReq.ProtoReflect.Descriptor instead.
func (*GetDepthReq) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{0}
}

func (x *GetDepthReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDepthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 订单簿版本
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 卖盘
	Asks []*GetDepthResp_Position `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	// 买盘
	Bids []*GetDepthResp_Position `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *GetDepthResp) Reset() {
	*x = GetDepthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp) ProtoMessage() {}

func (x *GetDepthResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp.ProtoReflect.Descriptor instead.
func (*GetDepthResp) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{1}
}

func (x *GetDepthResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDepthResp) GetAsks() []*GetDepthResp_Position {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResp) GetBids() []*GetDepthResp_Position {
	if x != nil {
		return x.Bids
	}
	return nil
}

type GetTickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 多少条
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTickReq) Reset() {
	*x = GetTickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickReq) ProtoMessage() {}

func (x *GetTickReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickReq.ProtoReflect.Descriptor instead.
func (*GetTickReq) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{2}
}

func (x *GetTickReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTickResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickList []*GetTickResp_Tick `protobuf:"bytes,1,rep,name=tick_list,json=tickList,proto3" json:"tick_list,omitempty"`
}

func (x *GetTickResp) Reset() {
	*x = GetTickResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickResp) ProtoMessage() {}

func (x *GetTickResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickResp.ProtoReflect.Descriptor instead.
func (*GetTickResp) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{3}
}

func (x *GetTickResp) GetTickList() []*GetTickResp_Tick {
	if x != nil {
		return x.TickList
	}
	return nil
}

type GetTickerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetTickerReq) Reset() {
	*x = GetTickerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerReq) ProtoMessage() {}

func (x *GetTickerReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerReq.ProtoReflect.Descriptor instead.
func (*GetTickerReq) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickerReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickerList []*GetTickerResp_Ticker `protobuf:"bytes,1,rep,name=ticker_list,json=tickerList,proto3" json:"ticker_list,omitempty"`
}

func (x *GetTickerResp) Reset() {
	*x = GetTickerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResp) ProtoMessage() {}

func (x *GetTickerResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResp.ProtoReflect.Descriptor instead.
func (*GetTickerResp) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickerResp) GetTickerList() []*GetTickerResp_Ticker {
	if x != nil {
		return x.TickerList
	}
	return nil
}

type GetDepthResp_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数量
	Qty string `protobuf:"bytes,1,opt,name=qty,proto3" json:"qty,omitempty"`
	// 价格
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// 金额
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetDepthResp_Position) Reset() {
	*x = GetDepthResp_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp_Position) ProtoMessage() {}

func (x *GetDepthResp_Position) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp_Position.ProtoReflect.Descriptor instead.
func (*GetDepthResp_Position) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDepthResp_Position) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *GetDepthResp_Position) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetDepthResp_Position) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetTickResp_Tick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 价格
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// 数量
	Qty string `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	// 金额
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// 时间
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// taker是否是买单
	TakerIsBuyer bool `protobuf:"varint,6,opt,name=taker_is_buyer,json=takerIsBuyer,proto3" json:"taker_is_buyer,omitempty"`
}

func (x *GetTickResp_Tick) Reset() {
	*x = GetTickResp_Tick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickResp_Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickResp_Tick) ProtoMessage() {}

func (x *GetTickResp_Tick) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickResp_Tick.ProtoReflect.Descriptor instead.
func (*GetTickResp_Tick) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTickResp_Tick) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetTickResp_Tick) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *GetTickResp_Tick) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetTickResp_Tick) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetTickResp_Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickResp_Tick) GetTakerIsBuyer() bool {
	if x != nil {
		return x.TakerIsBuyer
	}
	return false
}

type GetTickerResp_Ticker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 最新价
	LatestPrice string `protobuf:"bytes,1,opt,name=latest_price,json=latestPrice,proto3" json:"latest_price,omitempty"`
	// 高
	High string `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	// 低
	Low string `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	// 成交额 计价币数量
	Volume string `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// 成交量 基础币数量
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// 涨跌幅
	PriceRange string `protobuf:"bytes,7,opt,name=price_range,json=priceRange,proto3" json:"price_range,omitempty"`
	// 24小时前的价格
	Last24Price string `protobuf:"bytes,8,opt,name=last24_price,json=last24Price,proto3" json:"last24_price,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetTickerResp_Ticker) Reset() {
	*x = GetTickerResp_Ticker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_rpc_pb_match_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickerResp_Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResp_Ticker) ProtoMessage() {}

func (x *GetTickerResp_Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_rpc_pb_match_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResp_Ticker.ProtoReflect.Descriptor instead.
func (*GetTickerResp_Ticker) Descriptor() ([]byte, []int) {
	return file_app_match_rpc_pb_match_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetTickerResp_Ticker) GetLatestPrice() string {
	if x != nil {
		return x.LatestPrice
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetPriceRange() string {
	if x != nil {
		return x.PriceRange
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetLast24Price() string {
	if x != nil {
		return x.Last24Price
	}
	return ""
}

func (x *GetTickerResp_Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_app_match_rpc_pb_match_proto protoreflect.FileDescriptor

var file_app_match_rpc_pb_match_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x22, 0xd8, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12,
	0x30, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x62, 0x69, 0x64,
	0x73, 0x1a, 0x4a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x69, 0x63,
	0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0xa2, 0x01, 0x0a, 0x04, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x74, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x24,
	0x0a, 0x0e, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x73, 0x5f, 0x62, 0x75, 0x79, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x73, 0x42,
	0x75, 0x79, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xad, 0x02, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c,
	0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72,
	0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0xdd, 0x01, 0x0a,
	0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69,
	0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x77,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x32, 0x34, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x32, 0x34, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x32, 0xad, 0x01, 0x0a,
	0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x11, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_match_rpc_pb_match_proto_rawDescOnce sync.Once
	file_app_match_rpc_pb_match_proto_rawDescData = file_app_match_rpc_pb_match_proto_rawDesc
)

func file_app_match_rpc_pb_match_proto_rawDescGZIP() []byte {
	file_app_match_rpc_pb_match_proto_rawDescOnce.Do(func() {
		file_app_match_rpc_pb_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_match_rpc_pb_match_proto_rawDescData)
	})
	return file_app_match_rpc_pb_match_proto_rawDescData
}

var file_app_match_rpc_pb_match_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_match_rpc_pb_match_proto_goTypes = []interface{}{
	(*GetDepthReq)(nil),           // 0: match.GetDepthReq
	(*GetDepthResp)(nil),          // 1: match.GetDepthResp
	(*GetTickReq)(nil),            // 2: match.GetTickReq
	(*GetTickResp)(nil),           // 3: match.GetTickResp
	(*GetTickerReq)(nil),          // 4: match.GetTickerReq
	(*GetTickerResp)(nil),         // 5: match.GetTickerResp
	(*GetDepthResp_Position)(nil), // 6: match.GetDepthResp.Position
	(*GetTickResp_Tick)(nil),      // 7: match.GetTickResp.Tick
	(*GetTickerResp_Ticker)(nil),  // 8: match.GetTickerResp.Ticker
}
var file_app_match_rpc_pb_match_proto_depIdxs = []int32{
	6, // 0: match.GetDepthResp.asks:type_name -> match.GetDepthResp.Position
	6, // 1: match.GetDepthResp.bids:type_name -> match.GetDepthResp.Position
	7, // 2: match.GetTickResp.tick_list:type_name -> match.GetTickResp.Tick
	8, // 3: match.GetTickerResp.ticker_list:type_name -> match.GetTickerResp.Ticker
	0, // 4: match.MatchService.GetDepth:input_type -> match.GetDepthReq
	2, // 5: match.MatchService.GetTick:input_type -> match.GetTickReq
	4, // 6: match.MatchService.GetTicker:input_type -> match.GetTickerReq
	1, // 7: match.MatchService.GetDepth:output_type -> match.GetDepthResp
	3, // 8: match.MatchService.GetTick:output_type -> match.GetTickResp
	5, // 9: match.MatchService.GetTicker:output_type -> match.GetTickerResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_match_rpc_pb_match_proto_init() }
func file_app_match_rpc_pb_match_proto_init() {
	if File_app_match_rpc_pb_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_match_rpc_pb_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickResp_Tick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_rpc_pb_match_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickerResp_Ticker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_match_rpc_pb_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_match_rpc_pb_match_proto_goTypes,
		DependencyIndexes: file_app_match_rpc_pb_match_proto_depIdxs,
		MessageInfos:      file_app_match_rpc_pb_match_proto_msgTypes,
	}.Build()
	File_app_match_rpc_pb_match_proto = out.File
	file_app_match_rpc_pb_match_proto_rawDesc = nil
	file_app_match_rpc_pb_match_proto_goTypes = nil
	file_app_match_rpc_pb_match_proto_depIdxs = nil
}
