// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: app/match/rpc/pb/match.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MatchService_GetDepth_FullMethodName  = "/match.MatchService/GetDepth"
	MatchService_GetTick_FullMethodName   = "/match.MatchService/GetTick"
	MatchService_GetTicker_FullMethodName = "/match.MatchService/GetTicker"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServiceClient interface {
	// 获取深度
	GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error)
	// 获取tick实时成交
	GetTick(ctx context.Context, in *GetTickReq, opts ...grpc.CallOption) (*GetTickResp, error)
	// 获取ticker
	GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResp, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error) {
	out := new(GetDepthResp)
	err := c.cc.Invoke(ctx, MatchService_GetDepth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetTick(ctx context.Context, in *GetTickReq, opts ...grpc.CallOption) (*GetTickResp, error) {
	out := new(GetTickResp)
	err := c.cc.Invoke(ctx, MatchService_GetTick_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResp, error) {
	out := new(GetTickerResp)
	err := c.cc.Invoke(ctx, MatchService_GetTicker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility
type MatchServiceServer interface {
	// 获取深度
	GetDepth(context.Context, *GetDepthReq) (*GetDepthResp, error)
	// 获取tick实时成交
	GetTick(context.Context, *GetTickReq) (*GetTickResp, error)
	// 获取ticker
	GetTicker(context.Context, *GetTickerReq) (*GetTickerResp, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatchServiceServer struct {
}

func (UnimplementedMatchServiceServer) GetDepth(context.Context, *GetDepthReq) (*GetDepthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepth not implemented")
}
func (UnimplementedMatchServiceServer) GetTick(context.Context, *GetTickReq) (*GetTickResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTick not implemented")
}
func (UnimplementedMatchServiceServer) GetTicker(context.Context, *GetTickerReq) (*GetTickerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicker not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_GetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetDepth(ctx, req.(*GetDepthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetTick(ctx, req.(*GetTickReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetTicker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetTicker(ctx, req.(*GetTickerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepth",
			Handler:    _MatchService_GetDepth_Handler,
		},
		{
			MethodName: "GetTick",
			Handler:    _MatchService_GetTick_Handler,
		},
		{
			MethodName: "GetTicker",
			Handler:    _MatchService_GetTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/match/rpc/pb/match.proto",
}
