// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameCoin = "coin"

// Coin mapped from table <coin>
type Coin struct {
	ID        uint32                `gorm:"column:id;primaryKey;autoIncrement:true;comment:币种ID，也是主键ID" json:"id"`
	CoinName  string                `gorm:"column:coin_name;not null;comment:币种名称" json:"coin_name"`
	Prec      int32                 `gorm:"column:prec;not null;comment:币种精度，小数位保留多少" json:"prec"`
	CreatedAt uint32                `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`
	UpdatedAt uint32                `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"softDelete:unix" json:"deleted_at"`
}

// TableName Coin's table name
func (*Coin) TableName() string {
	return TableNameCoin
}
