// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameCoin = "coin"

// Coin mapped from table <coin>
type Coin struct {
	ID        uint32                `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	CoinID    int32                 `gorm:"column:coin_id;not null;comment:币种ID" json:"coin_id"`            // 币种ID
	CoinName  string                `gorm:"column:coin_name;not null;comment:币种名称" json:"coin_name"`        // 币种名称
	Prec      int32                 `gorm:"column:prec;not null;comment:币种精度，小数位保留多少" json:"prec"`          // 币种精度，小数位保留多少
	CreatedAt uint32                `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt uint32                `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`      // 修改时间
	DeletedAt soft_delete.DeletedAt `gorm:"softDelete:unix" json:"deleted_at"`                              // 删除时间
}

// TableName Coin's table name
func (*Coin) TableName() string {
	return TableNameCoin
}
