// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameErrorCode = "error_code"

// ErrorCode mapped from table <error_code>
type ErrorCode struct {
	ID            int32                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ErrorCodeID   int32                 `gorm:"column:error_code_id;not null" json:"error_code_id"`
	ErrorCodeName string                `gorm:"column:error_code_name;not null" json:"error_code_name"`
	Language      string                `gorm:"column:language;not null" json:"language"`
	CreatedAt     uint32                `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     uint32                `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt     soft_delete.DeletedAt `gorm:"softDelete:unix" json:"deleted_at"`
}

// TableName ErrorCode's table name
func (*ErrorCode) TableName() string {
	return TableNameErrorCode
}
