// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSymbol = "symbol"

// Symbol mapped from table <symbol>
type Symbol struct {
	ID            uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SymbolName    string `gorm:"column:symbol_name;not null;comment:交易对名称" json:"symbol_name"`         // 交易对名称
	SymbolID      int32  `gorm:"column:symbol_id;not null;comment:交易对id" json:"symbol_id"`             // 交易对id
	BaseCoinID    uint32 `gorm:"column:base_coin_id;not null;comment:基础币ID" json:"base_coin_id"`       // 基础币ID
	BaseCoinName  string `gorm:"column:base_coin_name;not null;comment:基础币名称" json:"base_coin_name"`   // 基础币名称
	BaseCoinPrec  int32  `gorm:"column:base_coin_prec;not null;comment:基础币精度" json:"base_coin_prec"`   // 基础币精度
	QuoteCoinID   uint32 `gorm:"column:quote_coin_id;not null;comment:计价币ID" json:"quote_coin_id"`     // 计价币ID
	QuoteCoinName string `gorm:"column:quote_coin_name;not null;comment:计价币名称" json:"quote_coin_name"` // 计价币名称
	QuoteCoinPrec int32  `gorm:"column:quote_coin_prec;not null;comment:计价币精度" json:"quote_coin_prec"` // 计价币精度
	CreatedAt     uint32 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`            // 创建时间
	UpdatedAt     uint32 `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`            // 修改时间
	DeletedAt     uint32 `gorm:"column:deleted_at;not null;comment:删除时间" json:"deleted_at"`            // 删除时间
}

// TableName Symbol's table name
func (*Symbol) TableName() string {
	return TableNameSymbol
}
