// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint32                `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nickname  string                `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`
	Username  string                `gorm:"column:username;not null;comment:用户名" json:"username"`
	Password  string                `gorm:"column:password;not null" json:"password"`
	CreatedAt uint32                `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt uint32                `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"softDelete:unix" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
